export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS"
export const REGISTER_SUCCESS ='REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGOUT = 'LOGOUT'
export const BLOGCREATE = 'BLOGCREATE'
export const BLOGVIEW ='BLOGVIEW'
export const BLOGUPDATE ='BLOGUPDATE'
export const BOLGDELETE ='BLOGDELETE'
export const ALLBLOGS = 'ALLBLOGS'
export const BLOG_LOAD_SUCCESS = 'BLOG_LOAD_SUCCESS'

